### ISSUE TITLE
Error 404 (Not Found): GET api/directories

### ISSUE THREAD

**Issue by jaykay06** [cakebox/cakebox#118]
Bonjour à tous :)

Petit soucis apparemment fréquent à l'utilisation de Cakebox-light + transmission.

J'ai donc ce message d'erreur dans Cakebox.

Des idées ?

Pas de sous domaine ou d'alias, j'atteris sur ma box via les adresses suivantes :
transmission : http://xxx.xxx.xxx.xxx:6666/torrent/
et
cakebox : http://xxx.xxx.xxx.xxx/cakebox/public/#/

Par avance merci :)

PS : soyez indulgent, je débute :)

**Comment by sinc59** [comment]
Bonjour,
je passe surement un peu tard mais je pense avoir une solution à ton problème.
Lors de l'installation d'apache un VirtualHost est crée par défault. Vous pouvez le supprimer en utilisant :
rm -f /etc/apache2/{sites-enabled,sites-available}/000-default.conf

Puis un reload de apache:
service apache2 reload

En espérant que ça aide quelqu'un :)

**Comment by VincentSalavert** [comment]
Bonjour,
sinc59 je vénére!!! J'y ai passé quelques heure mais merci pour pour solution!!! 
Aux autres qui passeront par là, n'oubliez pas aussi de disable le 000-default.conf avec la commande suivante: 
a2dissite 000-default.conf
