### ISSUE TITLE
Suggestions : Video suivante et mode edition

### ISSUE THREAD

**Issue by lokiiiii** [cakebox/cakebox#122]
Bonjour,
Tout d'abord, toutes mes félicitations, j'adore vraiment énormément cakebox / cabox-light.
J'ai passé beaucoup de temps sur cakebox et je me suis décidé il n'y a pas longtemps à passer sur cakebox-light, surtout pour l'intégration du html5.

J'ai deux petits regrets cependant, en comparant avec cakebox 1er du nom:

Comme dis dans un ticket déjà ouvert, la possibilité de revenir à la vidéo précédente ou de passer à la vidéo suivante était vraiment top, surtout lorsqu'on navigue dans les répertoires de séries, c'est un peu pénible du coup de devoir revenir à la page précédente pour retrouver la vidéo à lancer ensuite. (c'est pas insurmontable évidemment, c'est juste un luxe qui pourrait agrémenter ce super soft)
Ensuite

Ensuite, et surtout: ce qui me manque énormément comparé à cakebox, c'est le mode édition et la possibilité de trier ses dossiers et fichiers directement depuis cakebox, sans devoir ouvrir un ssh pour le faire manuellement en ligne de commande...

Encore une fois, tout ceci n'est que du luxe, encore un gros bravo !!!

**Comment by mpgn** [comment]
check https://github.com/Cakebox/cakebox/releases/tag/v1.8.6

Créer un dossier est maintenant possible
Vidéo suivante/précédente c'est bon

Pour le mode édition on attend d'implémenter un méthode d'authentification :)
