### ISSUE TITLE
Messages d'erreurs

### ISSUE THREAD

**Issue by tuxity** [cakebox/cakebox#128]
Il faudrait (re)voir les messages d'erreurs pour faire en sorte qu'un message soit + explicite pour un utilisateur lambda et directement visible. Et + détaillés et dans la console pour nous.

Cela nous evitera d'avoir des tickets pour des problèmes de droits par exemple.

**Comment by Tuxity** [comment]
Notes:
- Utiliser les erreurs HTTP
- Creer des codes d'erreur de l'app dans chaque try/catch, if etc...
- Envoyer un objet qui contient le code d'erreur de l'app + message (non explicite)
- Cree une page sur le wiki pour les recenser et expliquer
