### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by Tuxity** [Cakebox/cakebox#132]
Check how we can make Google's Chromecast compatible with Cakebox video players https://developers.google.com/cast/

**Comment by denouche** [comment]
Rhooo ça serait vraiment génial ça.
Même déjà l'angular-vlc, parce que le player web VLC actuel est un peu laborieux à utiliser (pas d'avance/retour rapide, pas moyen de naviguer dans un film etc).
La branch angular-vlc-player est fonctionnelle ?

**Comment by martialdidit** [comment]
@denouche Pour vlc-angular on attend que l'équipe VLC sorte une nouvelle version de l'API pour le player (courrant janvier/fevrier)

**Comment by denouche** [comment]
Ah super cool !
C'est prévu dans la version 2.2 de VLC ?
Merci pour tout le boulot, le résultat est génial !

**Comment by mpgn** [comment]
aborted !
