### ISSUE TITLE
Authentification avec Silex + SSL

### ISSUE THREAD

**Issue by fma16** [cakebox/cakebox#134]
Bonjour tout le monde.

Je voudrais proposer une nouvelle fonctionnalité à Cakebox aujourd'hui. Le plus gros du travail ayant été effectué, il reste certain détails à polir, notamment l'authentification à Cakebox. 
Dans la lignée du projet "[Let's Encrypt](https://letsencrypt.org/)" de la EFF et Mozilla, qui a pour objectif de faciliter la création et la mise en place de certificats SSL gratuitement, je pense qu'il serait intéressant de mettre en place un système d'authentification plus pratique et performant. L'authentification par .htaccess est bien pour commencer, mais ce n'est pas un modèle de simplicité, et son UX est minable (et surtout pas compatible avec un gestionnaire de mots de passe comme 1Password ou Dashlane). De plus, tout les identifiants passent en clair, ce qui aujourd'hui est problématique.

J'aimerais donc savoir si il était possible d’implémenter une nouvelle solution d'authentification pour Cakebox, notamment grâce à "[SecurityServiceProvider](http://silex.sensiolabs.org/doc/providers/security.html)" de Silex ou autre, avec la possibilité d'encrypter tout ça avec un certificat SSL-TLS (en attendant la disponibilité de Let's Encrypt, StartSSL semble proposer des certificats basiques gratuits - voici [un guide d'Ars Technica](http://arstechnica.com/security/2009/12/how-to-get-set-with-a-secure-sertificate-for-free/)).

Merci pour vos conseils.

**Comment by Tuxity** [comment]
Un systeme de login est a ajouter egalement, en utilisant un fichier (Ini ?) coté api contenant login, pass (encrypté), et droits.

**Comment by mpgn** [comment]
pass (chiffré)**

**Comment by mpgn** [comment]
Problème de rejeux possible par contre !

**Comment by mpgn** [comment]
voir branch https://github.com/Cakebox/cakebox/tree/auth

Je précise qu'il convient à l'utilisateur d'installer SSL ou non. On se charge juste de l'authentification de l'utilisateur.

**Comment by L3o-pold** [comment]
J'ai également commencé à travailler sur l'authentification. Théoriquement, il ne me manquait que l'envoi du token à l'API dans chaque requête.

Quelques remarques concernant les derniers commits sur la branch Auth:

- Pourquoi utiliser les cookies et pas uniquement le token généré par l'API ?

- Les erreurs 410 devraient à mon sens être gérées dans une seule fonction du type:

`$app->before(function () {
});`

- Petite faute de frappe sur $app->get("/api/diconnect",  __NAMESPACE__ . "\\disconnect");

Je peux commit mes différentes modifications si cela peut vous avancer sur certains points.

**Comment by mpgn** [comment]
@L3o-pold j'ai fait au plus simple. Mais oui @Tuxity  voulait aussi utiliser les tokens avec https://jwt.io/ donc pourquoi pas. 
Comme tu as du le voir on a drop la **v2.0.0** pour se concentrer sur la **v1.9.0**

Niveau auth j'ai fait le front-end avec le login page, pour le backend du coup comme Silex est vraiment pas très agréable à utiliser de mon point de vu j'évite de trop toucher et je me contente du minimum avec une fonction login et une autre qui vérifie si le cookie est valide.
Les paramètre du login sont envoyé en GET parce que Silex n'aime pas mon POST et ne veut pas récupérer les paramètres. (un truc à changer)

Pour l'erreur 410 c'était pour différencier des autres erreurs, je pense même pas que 410 soit l'erreur à utiliser.

Il manque aussi la gestion des users avec les fichiers `default.php`, `user1.php` suivant le login rentré par l'utilisateur si il active l'auth.

Il y a aussi des erreurs sur des fonctions `addDirectory()`, `removeDirectory()` ou si je renvoie la nouvelle liste d'éléments il me sort une erreur et ne rafraîchit pas le scope, du coup je refresh toute la page (honte à moi)...
