### ISSUE TITLE
Utilisation de Filebot pour organiser ces fichiers

### ISSUE THREAD

**Issue by krmshsh** [Cakebox/cakebox#154]
Bonjour à tous,

J'ai installer dernièrement filebot pour un usage avec "Plex"  plus info ici : http://mondedie.fr/viewtopic.php?id=6388, mais je me suis pas arrêté là j'ai voulu l'utilisé pour la cakebox, donc j'ai pointé le dossier de recherche sur le dossier Media ou filebot génère ces liens.

Le problème cakebox affiche les images des jaquettes de films et séries mais les vidéo non (ou tout du moins les simlink créé par filebot).

Pouvez vous m'aider ?

Merci d'avance.

**Comment by tap3** [comment]
Salut,
enfaite cakebox ne gère pas les symlink, je me penche dessus si je trouve une parade je te ferais un retour ;)
En attendant tu peut toujours faire pointé cakebox sur ton dossier downloads ou torrents !
