### ISSUE TITLE
Lightbox / zoombox pour voir les images

### ISSUE THREAD

**Issue by Krostar** [Cakebox/cakebox#167]
Bonsoir,

Je découvre cakebox, et je ne vois pas le moyen de visualiser une image sans la télécharger (ou sans l'ouvrir dans un nouvel onglet).

J'ai tenté de rajouté au code une class zoombox(http://grafikart.github.io/Zoombox/), mais sans succès, je fais péter angularjs à chaques fois (et puisque je ne connais pas du tout ce framework, je n'ai pas la foi d'aller beaucoup plus loin dans mes expérimentations).

Est-il envisageable d'implémenter ce genre de feature ?
Si non, pourriez vous me dire comme faire pour que je le fasse sur mon server ?

Cordialement,
Krostar.

**Comment by Magicalex** [comment]
t'as installé jquery?

**Comment by mpgn** [comment]
Salut !

La prévisualisation c'est une bonne idée mais Zoombox est peut être un peux overkill pour ca non ?
