### ISSUE TITLE
Suggestion infos pour tous les utilisateurs via BetaSeries + langue résumés

### ISSUE THREAD

**Issue by Galixte** [cakebox/cakebox#169]
Salut,

serait-il possible d’avoir les informations fournies par BetaSeries, pour les épisodes des séries TV donc, afin que chaque utilisateur de cakebox puisse y accéder sans avoir à configurer un compte BetaSeries pour chaque fichier /config/utilisateur.php ?

Par exemple on renseignerait dans un ficher les identifiants et la clé API d’un compte BetaSeries pour que soient récupérées les informations sur les épisodes des séries TV (résumé/note/date) et affichées lorsqu’un utilisateur de cakebox visionne un épisode mais sans avoir la fonction « Marquer l'épisode comme vu sur BetaSeries » qui s’affiche.

Pour cette dernière fonctionnalité, il faudrait faire comme actuellement, renseigner les informations du compte BetaSeries appropriées au fichier PHP de l’utilisateur en question.

J’espère avoir été clair dans mes propos. ;)

---

Comment afficher le résumé de l’épisode de série TV fourni par BetaSeries en français ? Le reste étant bien affiché en français : la note et la date de diffusion ains que le message « Marquer l'épisode comme vu sur BetaSeries ».

EDIT: ok, il semble que sur BetaSeries les résumés ne soient pas en français, c’est bien ça ?

**Comment by Tuxity** [comment]
Hmm en effet c'est pas bete.

Ce que je pensais faire c'était utiliser http://thetvdb.com et https://www.themoviedb.org pour recuperer les informations de l'ep/film, et Betaserie pour le marquer comme vu uniquement. Il me semble que c'est dispo en plusieurs langues sur ces sites, mais pas sur, si ca se trouve ca va donner le meme resultat que BS.

**Comment by Galixte** [comment]
Oui c’est proposé en plusieurs langues pour les deux sites.
