### ISSUE TITLE
Cakebox ne lit pas les dossiers liés (alias ou raccourcis, c'est la même chose)

### ISSUE THREAD

**Issue by furest** [Cakebox/cakebox#171]
Bonsoir,
Je suis en train de configurer mon cakebox pour plusieurs utilisateurs.
Le dossier du premier utilisateur est le dossier /home/rtorrent/Downloads/ et celui du second est /home/rtorrent/Autres/
J'aimerais que certains dossiers de mon user 1 (dossier Downloads)  puissent être visibles dans le cakebox du user 2. Pour cela j'ai fait un ln -s  /home/rtorrent/Downloads/Dossier  /home/rtorrent/Autres/Dossier. Cependant, quand cakebox tente de l'ouvrir, il le met dans l'url (un "/Dossier" de plus s'ajoute) mais reste dans le dossier principal... 
Du coup j'ai du copier/coller les données purement et simplement mais ça prend inutilement de l'espace disque...
Y a-t-il quelque chose de spécial à faire ou ais-je juste fais une fausse manip? Sinon serait-ce un projet pour cakebox 2? :)
Furest

**Comment by Tuxity** [comment]
See #154

Je penserai a ca pour la version 2 ;)
