### ISSUE TITLE
[STREAMING] Alias "/access/" et problème de port

### ISSUE THREAD

**Issue by JimmyCastiel** [Cakebox/cakebox#172]
Bonjour,

J'ai installé aujourd'hui cakebox-light version 1.8.3 sur ma débibox fonctionnant sous debian 8.

J'arrive à accèder à l'interface, à lister les fichiers cependant ayant changé dans la configuration du port du virtualhost dédié à cakebox pour le positionner sur le port 81, le port 80 étant déjà occupé, je me suis rendu compte que je ne pouvais pas lire de vidéo car la requête à l'alias "/access/" est réalisée sur le port 80 qui n'est pas écouté.

Est-ce normal ? Dois-je intervenir d'une manière quelquonce ou dois-je attendre une mise à jour du code ?

Merci par avance

**Comment by mpgn** [comment]
Salut,

Regarde dans ton fichier de conf cakebox Apache, (`/etc/apache2/sites-available`) au début tu as `<VirtualHost *:80>`, change avec le port 81 :)

**Comment by JimmyCastiel** [comment]
Salut,

Merci pour cette solution, mais c'est ce que j'ai fais quand je dis que j'ai "changé dans la configuration du port du virtualhost dédié à cakebox pour le positionner sur le port 81".

J'ai trouvé d'où vient le problème, il s'agit d'un oubli dans le fichier "webplayer.js" que l'on peut trouver dans "public/app/directive/".
La ligne 18 ressemble à ceci :
"scope.url = $location.protocol() + "://" + $location.host() + data.url;"
alors qu'elle devrait ressembler à cela :
"scope.url = $location.protocol() + "://" + $location.host() + ":" +  $location.port() + data.url;".

Maintenant le streaming fonctionne.

Il faudrait peut-être faire une mise à jour du git pour le prendre en compte :)

Merci pour ton aide mpgn.

**Comment by JimmyCastiel** [comment]
pull request effectuée

**Comment by mpgn** [comment]
Bien vu !

**Comment by mpgn** [comment]
check https://github.com/Cakebox/cakebox/pull/173

**Comment by 2edff206** [comment]
J'ai téléchargé cakebox hier et j'ai toujours le même soucis. La mise à jour n'a-t-elle pas été pris en compte ?

**Comment by mpgn** [comment]
@2edff206 je vais m'en charger, le commit est push sur la branch v2 et non master. Je vais push le code aussi sur master :)
