### ISSUE TITLE
cakebox ne m'affiche rien

### ISSUE THREAD

**Issue by patriarch** [Cakebox/cakebox#179]
//passage inutile ou je raconte ma vie
je dois être maudis avec vous ...

J'ai voulu installer cakebox, le scipt complet n'a pas fonctionner (installer de composer non realiser)
je me suis donc attelé à une installation manuel, après une magnifique erreur à votre commande pour nodejs (installer le paquet npm sort une érreur alors qu'il est installé directement avec le paquet nodejs).

//partie utile 
une foie mon installation fini je lance donc le script pour l'alias et la c'est drame

quand je vais sur ma cakebox avec mon navigateur elle m'affiche (avec le fond qui lui s'affiche):

Cakebox

    NAVBAR.LOOK_INTO
    NAVBAR.ABOUT

et c'est tout .... j'ai essayé de passer par le script pour mettre en sous domaine mais même résultat

**Comment by ahyear** [comment]
qu'affichent les log d'erreur apache?

**Comment by patriarch** [comment]
pour le fichier cakebox.patriarch.fr-access.log
https://gist.github.com/patriarch/4259863b2fd0bf7abf56

je n'ai rien dans cakebox.patriarch.fr-error.log

et voici error.log
https://gist.github.com/patriarch/74bbc5043024701a7645

**Comment by L3o-pold** [comment]
Quel est le retour de cette commande dans le répertoire front/ ?
```javascript
bower update 
```

**Comment by patriarch** [comment]
question bête ou est le répertoire front/ ? 
je ne le trouve pas dans mon dossier d'installation

**Comment by L3o-pold** [comment]
Sur la version 1.x, il faut executer cette commande depuis le répertoire principal, ou se situe le fichier bower.json

**Comment by ahyear** [comment]
Selon les logs il me semble que c'est la version master et non la 2.0 qui ai été installée.

**Comment by ahyear** [comment]
les dependances n'ont pas été installée. L3o-pold a raison il faut lancer bower update depuis le repertoire racine de la cakebox.

l'installation a été faite en root?

**Comment by patriarch** [comment]
c'était bien ça, en lançant le bower update en root cakebox fonctionne 

j'avais fait l'installation en root pourtant

**Comment by ahyear** [comment]
et tu avais bien ajouté --allow-root ?

**Comment by patriarch** [comment]
si mes souvenirs sont bon j'ai installé les près-requis manuellement puis je suis passé par le script pour le reste et je l'avais lancé en root

qu'apporte la version 2 pour voir si je tente d'y passer ?

**Comment by patriarch** [comment]
en tout cas merci de votre aide

**Comment by ahyear** [comment]
la version 2.0 est encore en developpement... 
c'est pas encore le moment de l'essayer ^^

peut tu fermer ton ticket si tout fonctionne bien?
merci
