### ISSUE TITLE
Not found 

### ISSUE THREAD

**Issue by mxkiller** [Cakebox/cakebox#180]
J'ai installé cakebox sur un vps debian mais je recontre un soucis. Je peut voir tout mes fichiers, jusque la tout est correct. Lorsque je clique sur un film j'ai donc comme si je pouvait le lire mais en cliquant sur le play rien ne se passe. Lorsque j'appuie sur télécharge j'ai ceci

Not Found
The requested URL /access/XXXX.avi was not found on this server.

De quoi cela peut venir ?

**Comment by Micdu70** [comment]
Bonjour,

Pour pouvoir t'aider, il faudrait savoir quel est ton serveur web ( Apache, Nginx, etc. ) et sa version.

;)

**Comment by L3o-pold** [comment]
Il ne faut pas oublier de configurer le serveur web. Les exemples sont disponibles [ici]( https://github.com/Cakebox/cakebox/tree/master/webconf-example). 

Vu l'erreur 404, je pense qu'il n'y a pas l'alias nécessaire vers le répertoire vidéo.

Comme dit Micdu70, avec plus d'informations sur la version et la configuration de ton serveur Web, nous serons plus à même de t'aider.

**Comment by ahyear** [comment]
sous apache, il se peut aussi qu'un fichier de virtualhost par defaut parasite celui créé par le script...
dans ce cas retirer les balises de virtualhost du fichier generé par cakebox a souvent suffit a regler le probleme.

**Comment by mxkiller** [comment]
Merci à tous mais j'ai trouvé, j'avais mal écrit le dossier à scanner dans le virtual host, il était différent de la configuration cakebox
