### ISSUE TITLE
Installation de rutorrent ?

### ISSUE THREAD

**Issue by Nico83500** [Cakebox/cakebox#181]
Bonjour,
J'ai utilisé il y a quelques temps l'ancien script qui permettait de créer une Seedbox rapidement (rutorrent et cakebox). Est-ce qu'il existe toujours un script ou un tuto pour installer le tout ?
Merci !

**Comment by Magicalex** [comment]
Non ce script n'existe plus pour cakebox-light qui est maintenant devenu cakebox.
je peux te conseiller ce script pour installer rutorrent : https://github.com/exrat/rutorrent-bonobox
et suivre ce tuto pour installer cakebox http://mondedie.fr/viewtopic.php?id=5314

**Comment by Nico83500** [comment]
Merci pour la réponse. Je n'ai jamais utilisé ngix, seulement apache. J'aurais préféré un Ubuntu en OS mais je m'adapterai si jamais ;-)

**Comment by mpgn** [comment]
@Nico83500 tu peux utiliser Apache, le tuto reste valide, il te suffit juste de remplacer la partie nginx par le fichier de conf apache https://github.com/Cakebox/cakebox/blob/master/webconf-example/apache2-alias.conf.example

**Comment by Nico83500** [comment]
Oui mais comme je débute sur Linux je cherchais quelque chose de facile à suivre.
J'ai réussi à mettre en place cakebox sur Apache par contre impossible d'utiliser le .htaccess, je ne sais pas si j'ai mal fait quelque chose ou si mon Kimsufi fait des siennes... Je vais tenter d'utiliser du Debian à la place d'Ubuntu, ca me fera manipuler un peu :)

**Comment by Nico83500** [comment]
Bon j'ai réussi à installer cakebox grâce au tuto de magicalex mais par contre il n'y a plus de mode édition dans cakebox ? Créer un dossier, supprimer un fichier, etc...

**Comment by Magicalex** [comment]
Supprimer un dossier si, par contre créer et déplacer non.
