### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by tuxity** [cakebox/cakebox#183]
Try to get new ideas for the version 2.0.0 design, we kinda stuck to make things better without it.

**Comment by mpgn** [comment]
Et voila un début en mockup, j'ai intégré les fonctionnalités de la verison 2.0

![9da6aa3ee6b2095b030c1b84dcc7b6e5](https://cloud.githubusercontent.com/assets/5891788/12023113/8192954e-ad96-11e5-89a8-f55310edfdeb.png)
![be092c688d1a79b3513fd4c522eb99d7](https://cloud.githubusercontent.com/assets/5891788/12023130/a7e245d2-ad96-11e5-97d7-14da7b771fd5.png)

**Comment by denouche** [comment]
Intéressant !

Si je peux me permettre quelques suggestions / questions :
- Faire en sorte que l'affichage de l'espace occupé, total et restant soit
optionnel. Par exemple dans mon cas j'ai mis un système de quotas par user
et donc les chiffres affichés seraient tous erronés.
- comment seront gérés l'enregistrement des favoris ? Il va falloir ajouter
une bdd juste pour ça ?
- comment va fonctionner la feature de partage ? Dans le cas d'une basic
authentication avec un apache devant, ça ne fonctionnera pas ?

Merci !
Le 28 déc. 2015 7:11 PM, "Martial Puygrenier" <notifications@github.com> a
écrit :

**Comment by mpgn** [comment]
Salut @denouche 

> - Faire en sorte que l'affichage de l'espace occupé, total et restant soit
optionnel. Par exemple dans mon cas j'ai mis un système de quotas par user
et donc les chiffres affichés seraient tous erronés.

Bonne remarque !

> - comment seront gérés l'enregistrement des favoris ? Il va falloir ajouter
une bdd juste pour ça ?

On va éviter une bdd, un simple xml ou autre fait l'affaire

> comment va fonctionner la feature de partage ? Dans le cas d'une basic
authentication avec un apache devant, ça ne fonctionnera pas ?

L'authentification basic va être supprimé au profit d'une vraie authentification
L'idée de la feature c'est de pouvoir partager un film et que l'utilisateur ne puisse voir seulement se film sans pouvoir remonter et voir autre chose. C'est encore en phase d'idée il faut y réfléchir plus en détaille :)

**Comment by mpgn** [comment]
Je précise aussi que l'on pense intégrer optionnellement l'api track.tv ou/et autres.

**Comment by mpgn** [comment]
Je poste un autre mockup de la page player.
![24adc8af9a8e70feaf193a6a86d08ea3](https://cloud.githubusercontent.com/assets/5891788/12053113/1015fab0-af16-11e5-926b-2cdb37b621d2.png)

**Comment by CooperBarrett** [comment]
Salut j'espère être où il faut, j'aurai une ou deux propositions : 

1) **avoir en option la possibilité d'afficher ou non les dossier vide**. En effet j'utilise pour ma part Sickrage qui me crée systématiquement un dossier à chaque série donc lorsque la saison est finie et que j'ai supprimé les épisodes, je me retrouve avec pas mal de dossiers vides. Le fait de ne pas les voir serait un confort visuel. 

2) **Afficher les derniers téléchargements**. Ça c'est beaucoup plus gadget mais comme j'utilise cakebox en multi utilisateurs avec ma famille, ça leurs permettraient de voir les derniers téléchargement en un coup d'oeil. Pourquoi ne pas choisir les séries pour lesquelles on souhaite voir les derniers téléchargements (bon ok, je m'emballe un peu...)

Voilà, merci pour le boulot effectué, ça va faire quelques années que je m'en sert maintenant, c'est toujours le meilleur (simplicité, rapidité) !
