### ISSUE TITLE
Chargement des fichiers et rien ne se passe

### ISSUE THREAD

**Issue by Matkill** [Cakebox/cakebox#186]
Bonjour,

J'ai enfin réussi à installer cakebox avec l'installation automatique (j'ai galéré pendant quelques heures avec plusieurs problèmes aha) 

Il m'en reste un je touche au but ! ça met  "Chargement des fichiers, veuillez patienter ..." et c'est tout. Dans le debugger de firefox j'ai ceci :

"Error: [$resource:badcfg] http://errors.angularjs.org/1.2.29/$resource/badcfg?p0=array&p1=object
z/<@http://cakebox.xxx.com/components/angular/angular.min.js:6:450
t/</f[d]/q<@http://cakebox.XXX.com/components/angular-resource/angular-resource.min.js:8:1
Ee/e/m.promise.then/K@http://cakebox.XXX.com/components/angular/angular.min.js:102:87
Ee/e/m.promise.then/K@http://cakebox.XXX.com/components/angular/angular.min.js:102:87
Ee/f/<.then/<@http://cakebox.XXX.com/components/angular/angular.min.js:103:259
Zd/this.$get</h.prototype.$eval@http://cakebox.XXX.com/components/angular/angular.min.js:114:28
Zd/this.$get</h.prototype.$digest@http://cakebox.XXX.com/components/angular/angular.min.js:111:109
Zd/this.$get</h.prototype.$apply@http://cakebox.XXX.com/components/angular/angular.min.js:114:360
l@http://cakebox.XXX.com/components/angular/angular.min.js:73:236
w@http://cakebox.XXX.com/components/angular/angular.min.js:78:250
ze/</y.onreadystatechange@http://cakebox.XXX.com/components/angular/angular.min.js:79:320
" angular.min.js:93:8

Error: data.version is undefined
$scope.app<@http://cakebox.XXX.com/app/controller/AppCtrl.js:18:1
t/</f[d]/q<@http://cakebox.XXX.com/components/angular-resource/angular-resource.min.js:9:298
Ee/e/m.promise.then/K@http://cakebox.XXX.com/components/angular/angular.min.js:102:87
Ee/f/<.then/<@http://cakebox.XXX.com/components/angular/angular.min.js:103:259
Zd/this.$get</h.prototype.$eval@http://cakebox.XXX.com/components/angular/angular.min.js:114:28
Zd/this.$get</h.prototype.$digest@http://cakebox.XXX.com/components/angular/angular.min.js:111:109
Zd/this.$get</h.prototype.$apply@http://cakebox.XXX.com/components/angular/angular.min.js:114:360
l@http://cakebox.XXX.com/components/angular/angular.min.js:73:236
w@http://cakebox.XXX.com/components/angular/angular.min.js:78:250
ze/</y.onreadystatechange@http://cakebox.XXX.com/components/angular/angular.min.js:79:320

Je n'ai pas trouvé sur internet comment résoudre ce problème. Une idée ?

Merci d'avance,

**Comment by mpgn** [comment]
Refait un `npm install && bower install` dans le dossier d'installe de cakebox

**Comment by Lisander27** [comment]
J'ai exactement le même probleme et je ne peux pas faire 

>  npm install

> npm`WARN enoent ENOENT: no such file or directory, open '/var/www/cakebox/package.json'

**Comment by mpgn** [comment]
Et bien est ce que le fichier ` /var/www/cakebox/package.json` existe ?

**Comment by Lisander27** [comment]
Bon j'ai finalement réinstaller et suis passer sous debian car ubuntu me sortais par les yeux ^^ .

Ducoup maintenant j'arrive bien a charger les fichiers mais une fois que je lance un de mes films en stream , la video ne charge pas ( fond noir ) et la durée est mal définis ( 4h30 au lieu de 1h30 ) .

Et bien sure VLC & DviX ne fonctionne pas

**Comment by mpgn** [comment]
Oui à moins d'activer NPAPI depuis chrome, VLC et DviX player sont obsolètes.

**Comment by Lisander27** [comment]
J'ai essayer mais justement ca fonctionne pas ou plus ^^'

**Comment by mpgn** [comment]
Sous Firefox DivX ça marche pour sur NPAPI n'est pas encore déprécié.

**Comment by Lisander27** [comment]
J'suis sous chrome donc y'a rien qui marche ^^ donc je vais utiliser IE en attendant ^^'
