### ISSUE TITLE
Error 404 (Not Found): GET api/directories pour ne pas vs surprendre

### ISSUE THREAD

**Issue by flop25** [Cakebox/cakebox#189]
Bonjour
j'ai lu les autres post
J'ai mis en 777 tout \cakebox tout \download et les deux sont cote à cote ; ils ont aussi tout les deux le même user:group. Et bien sûr je parle pour tous les ficheirs et dossier à l'intérieur aussi
et pourtant Error 404 (Not Found): GET api/directories 
plus généralement
GET rights 404 Not Found
GET app 404 Not Found
GET directories?path= 404 Not Found
j'ai fait qq recherche
find / -type d -name 'directories'
Rien
find / -type d -name 'api'
/usr/local/lib/node_modules/bower/lib/node_modules/github/api
/tmp/node-v5.5.0/doc/api
et c'est tout

Donc je penses que finalement c'est peut être plus un problème de fichier manquant non ? En tout cas merci d'avoir lu et merci d'avoir amélioré ce très joli script

**Comment by mpgn** [comment]
Tu accède à Cakebox avec quel url ?

**Comment by flop25** [comment]
ha oui j'ai oublié ça
quand j'ai vu dans le fichier config $app["cakebox.access"] = "/access/"; // Alias used in web server for direct access, je l'ai changé pour le vrai chemin url  "/foo/cakebox/public/" ; ça n'a pas amélioré

**Comment by mpgn** [comment]
Je repose ma question: 

Tu accède à Cakebox avec quel url ? et remet l'alias comme il était.

**Comment by flop25** [comment]
bar.truc/foo/cakebox/public
qui devient bar.truc/foo/cakebox/public/#/ en pratique

**Comment by mpgn** [comment]
Type: Erreur 404 (Not Found): GET api/directories/, et vous accédez à l'url via le dossier /public 
Résolution:

Le problème vient d'Apache ou Nginx, vous devez toujours accéder à Cakebox sans voir le dossier /public dans l'url. Vérifier bien d'avoir configuré correctement Apache via le script correspondant à votre version d'Apache.

**Comment by flop25** [comment]
oki doki
je vais aller revoir le rewriting
merci bonne nuit et à demain certainement

**Comment by flop25** [comment]
en effet c'est bien cela
je vous avouerai que je n'avais pas compris que il y avait de l'url rewriting et surtout que ce dernier était obligatoire 
Au final je me demande pourquoi vous passez par de l'url rewriting vu que cela peut poser nombres de problèmes assez techniques, ce qui contraste avec le coté KISS et 'à la portée de tout le monde'. Par ex si un novice avait eu mon problème qui est un CMS obligatoirement installé en dossier racine avec son url rewriting à bypasser, je pense qu'il aurait abandonné
en tout cas merci pour l’intervention rapide et le travail sur le script GG

**Comment by mpgn** [comment]
Bonne remarque, je prend note :)
