### ISSUE TITLE
Compatibilité New Browser

### ISSUE THREAD

**Issue by zarkos8** [cakebox/cakebox#191]
Bonjour,
Tous d'abord merci pour votre travail , votre solution cakebox est genial :) .
J'ai un petit soucis concernant la nouvelle maj firefox/chrome. Les nouvelles versions 64 bits n'incluent plus (apparemment par soucis de sécurité) les lecteurs vlc/divx . Ce qui rend l'utilisation possible de cakebox uniquement avec le lecteur html5 qui réduit considérablement le nombre de vidéos lisible.

Pensez-vous que l'intégration d'autres lecteurs compatible avec les nouvelles maj soit envisageable ?

**Comment by mpgn** [comment]
Et oui ! on y réfléchit, c'est pour ca que la v2 mais du temps :)

**Comment by L3o-pold** [comment]
Y a t-il déjà des pistes de solution à implémenter hormis un player flash par curiosité?

**Comment by mpgn** [comment]
C'est au entreprise comme VLC/divxx de fournir une nouvelle solution pour leurs produit. Mais comme la dit VLC sur irc ce n'est pas leurs priorité car cela ne touche "que" chrome pour l'instant et on peut activer npapi dans les options de chrome. (ce qui est pour moi une erreur de réfléchir comme ça mais bon...)
Google à déjà posté les pistes à suivre https://www.chromium.org/developers/npapi-deprecation (webRTC, HTML5 video) et à prévenue plus d'un an à l'avance. 

D'un autre coté, le player natif HTML5 évolue, on espérer la prise en charge des sous-titres comme prochaine évolution.
