### ISSUE TITLE
problème d'installation 

### ISSUE THREAD

**Issue by Tintin159** [Cakebox/cakebox#192]

**Comment by mpgn** [comment]
Il manque un `npm install & bower install` dans le dossier cakebox

**Comment by Tintin159** [comment]
et comment puis-je résoudre ce problème

**Comment by Tintin159** [comment]
je pense que j'ai trouvé la réponse => http://qsomazzi.fr/unix/installer-un-serveur-dedie-2

je vais le réinstaller manuellement /home/cakebox/.git

**Comment by mpgn** [comment]
sympas de supprimer ton poste, c'est très utiles pour les autres...
