### ISSUE TITLE
Problème htaccess

### ISSUE THREAD

**Issue by florosss** [Cakebox/cakebox#193]
Bonjour,
déjà merci pour cet utilitaire qui est génial.

J'ai un serveur kimsufi sur lequel j'ai installé cakebox light.
Le tout fonctionne très bien, excepté du htaccess pour pouvoir 
mettre un mot de passe.

j'ai bien activer le module apache comme expliqué sur la page 
https://github.com/Cakebox/cakebox/wiki/S%C3%A9curiser-Cakebox-light-via-htaccess-(BASIC)

j'ai créé mes deux fichiers  .htaccess et .htpasswd 

```
.htaccess
AuthName "Page d'administration protégée"
AuthType Basic
AuthUserFile "home/cakebox/.htpasswd"
Require valid-user
```
```
.htpasswd 
cakebox:$apr1$k7Fk3pfq$wR3Fl8xzmHCrG4JGqDpUe0
```
je les ai placé juste avant le dossier public c'est-à-dire /home/cakebox 
mais ça ne fonctionne pas j'ai une belle erreur 500 Internal Server Error 

```
log apache2
(2)No such file or directory: Could not open password file: /etc/apache2/home/cakebox/.htpasswd
```

**Comment by ahyear** [comment]
salut,
Essaye d'ajouter dans ton fichier .htaccess un slash avant le home ( /home/cakebox/.htpasswd)

**Comment by florosss** [comment]
génial ça marche merci  dire que j'ai cherché pendant des heures avant de faire le ticket je suis vraiment con
