### ISSUE TITLE
Multi utilisateur depuis la 1.8.6

### ISSUE THREAD

**Issue by MonsieurPlr** [Cakebox/cakebox#200]
Bonjour,
Depuis la MAJ de Cakebox en 1.8.6, en laissant mes fichiers de configuration précédentes (config/<user1>.php) la fonction "lire dans CakeBox" depuis rutorrent ne fonctionne plus car quand on ouvre n'importe quel lien sur CakeBox on est redirigé vers /login puis après vers l'accueil. Dans tous les cas on se retrouve sur l'accueil à cause de ce login.

On m'a parlé du fichier.auth.php pour résoudre ce problème, mais dans le wiki rien n'est marqué pour le configurer. Pouvez m'aider ?

Merci d'avance !

**Comment by Micdu70** [comment]
Bonsoir,
Il n'y a normalement aucun système de login dans la version 1.8.6 de Cakebox... ( présent uniquement dans la branche "master" )
Et sinon en cas de souci avec la 1.8.6, j'ai créé une version 1.8.7 (non-officielle) sur mon fork cakebox.

;)

**Comment by MonsieurPlr** [comment]
Merci, le fork cakebox c'est celui appelé "2.0.0" ?

**Comment by Micdu70** [comment]
Non, mon "fork" correspond au repo cakebox que j'ai "copié" pour moi, dont voici la page des releases => https://github.com/Micdu70/cakebox/releases 

P.S.: J'ai changé le numéro de version 1.8.7 en 1.8.6-1 pour éviter le message de mise à jour dans cakebox ( pour la version 1.8.6 ), puisque je n'ai pas changé le système de vérifications de mise à jour.

**Comment by mpgn** [comment]
Du as du prendre la master car dans la version 1.8.6 il n'y a pas cette histoire de login.

**Comment by MonsieurPlr** [comment]
Micdu70 > Merci ta version "non-officiel" a résolu mon problème :)
mpgn > J'ai du prendre la master surement, mon problème est réglé maintenant :)

Merci à vous deux en tout cas :)
