### ISSUE TITLE
Bad URL in bower.json

### ISSUE THREAD

**Issue by Bybou** [cakebox/cakebox#201]
Bad url : https://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js
Good url : https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/crypto-js/2.5.3-sha256.js

**Comment by mpgn** [comment]
Fixed 875ca5546ee1ff7f4f29eed160e2ff1738ab9274
