### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by thatann44** [Cakebox/cakebox#202]
Bonjour,

J'ai essayé de faire une update de cakebox et cela bloque a une etape : 
# cd /var/www/cakebox/
# git pull origin master
# bower update --allow-root

bower alertify#~0.3.10                                      validate 0.3.10 against https://github.com/fabien-d/alertify.js-shim.git#~0.3.10
bower sha256#*                                                 EHTTP Status code of 404

Depuis, j'accede bien mais je n'ai plus la liste de mes fichiers etc..

Comment puis-je faire?

**Comment by kanjusei** [comment]
C'est normal, L'url du paquet sha256 n'est pas bonne, il faut la modifier dans le fichier bower.json

avant:

`{
  "name": "cakebox-light",
  "version": "1.8.6",
  "dependencies": {
    "bootstrap": "3.3.x",
    "angular": "~1.5.5",
    "angular-i18n": "~1.5.5",
    "angular-resource": "~1.5.5",
    "angular-route": "~1.5.5",
    "angular-bootstrap": "~1.3.2",
    "alertify.js": "~0.3.11",
    "angular-translate": "~2.11.0",
    "angular-translate-loader-static-files": "~2.11.0",
    "zeroclipboard": "~2.2.0",
    "ng-clip": "~0.2.6",
    "ng-file-upload": "~12.0.4",
    "sha256": "https://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js",
    "angular-cookies": "~1.5.5"
  }
}`

après: 

`{
  "name": "cakebox-light",
  "version": "1.8.6",
  "dependencies": {
    "bootstrap": "3.3.x",
    "angular": "~1.5.5",
    "angular-i18n": "~1.5.5",
    "angular-resource": "~1.5.5",
    "angular-route": "~1.5.5",
    "angular-bootstrap": "~1.3.2",
    "alertify.js": "~0.3.11",
    "angular-translate": "~2.11.0",
    "angular-translate-loader-static-files": "~2.11.0",
    "zeroclipboard": "~2.2.0",
    "ng-clip": "~0.2.6",
    "ng-file-upload": "~12.0.4",
    "sha256": "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/crypto-js/2.5.3-sha256.js",
    "angular-cookies": "~1.5.5"
  }
}`

**Comment by thatann44** [comment]
Merci @kanjusei ! Fixed!
