### ISSUE TITLE
Page de connexion - Erreur Crypto JS

### ISSUE THREAD

**Issue by qrek** [cakebox/cakebox#206]
Bonjour,
Alors je viens de tout installer et configurer Cakebox selon les différents tutos que j'ai trouvé.
J'arrive à accéder à la page Cakebox, sauf que j'arrive sur l'écran de connexion et là rien ne se passe. Je n'ai trouvé aucun compte pour y accéder et lorsque que je clique sur l'input connexion j'ai une erreur CryptoJS "angular.js:13920 ReferenceError: CryptoJS is not defined"
En vous remerciant d'avance.

**Comment by mpgn** [comment]
Fixed on 875ca5546ee1ff7f4f29eed160e2ff1738ab9274 :)
