### ISSUE TITLE
activation rename/upload ?

### ISSUE THREAD

**Issue by remygrandin** [cakebox/cakebox#207]
Bonjour,

Je viens de reinstaller un cakebox tout neuf et je souhaitait notament utiliser la nouvelle fonction d'upload, mais je n'arrive pas a l'activer (ni la fonction de renommage ou de création). Pour autant, dans mon default.php, je pensais avoir activer cela

    /*
      User rights
    */
    $app["rights.canPlayMedia"] = true;
    $app["rights.canDownloadFile"] = true;
    $app["rights.canArchiveDirectory"] = true;
    $app["rights.canDelete"] = true;
    $app["rights.canCreate"] = true;
    $app["rights.canRename"] = true;
    $app["rights.canUpload"] = true;

**Comment by mpgn** [comment]
Salut,
Il faut utiliser le système de login pour avoir accès à ces fonctionnalité, tu peux re-tester ?

**Comment by remygrandin** [comment]
C'est ce que j'avais penser, mais vu que j'avais pu activer l’archivage et la suppression pour l'utilisateur anonyme par défaut, je pensais que ces autre fonctionnalités s'activerais aussi.

J'ai essayer d'utiliser l'authentification mais sans succès. Je pense que je dois me gourer quelque part dans la génération du hash du mot de passe. J'ai essayer de le générer avec ça : 

    echo password_hash ( hash('sha256', "test").'1589647820365489' , PASSWORD_BCRYPT , ['cost' => 12] )

la page de login ne me renvoi pas d'erreur dans l'UI mais un http 410 dans la console ("Wrong crendential")

est-ce que j'ai louper quelque chose ?

**Comment by mpgn** [comment]
C'est bien ça, tu peux aussi testé le match ici : https://www.dailycred.com/article/bcrypt-calculator
Tu as bien pris le dernier commit ?

Sinon, utilise le template auth par defaut avec comme identifiant :  user1/foo

**Comment by remygrandin** [comment]
J'ai mis a jour avec ton commit d'aujourd'hui mais ça ne marche toujours pas. 

Le calculator de dailycred me dit pourtan que le mot de passe hasher sha256 + salt  est bon (après avoir changer le 2y du debut en 2a (une histoire de version de la fonction php)
Le mot de passe foo par défaut marche correctement mais quand je remplace le hash dans auth.php, le nouveau ne marche pas

**Comment by mpgn** [comment]
Ok, les antislash dans le password il a pas trop aimé. Pull et re-test :)

**Comment by remygrandin** [comment]
Alleluia, ca marche ! 
L'upload et le create folder fonctionne mais dernier point noir : je ne trouve pas la fonction de renommage de ficher/dossier dans la web ui. Cette fonction a t'elle été implémenté ?

**Comment by mpgn** [comment]
Il fut un temps, quand je test maintenant j'obtiens : 

```
Catchable fatal error: Argument 1 passed to App\Controllers\Directories\rename() must be an instance of Silex\Application
```

j'ai laissé tombé... ca m’énerve trop Silex

**Comment by mpgn** [comment]
project is deprecated, check https://github.com/cakebox/cakebox/issues/216
