### ISSUE TITLE
Erreur mot de passe BCrypt

### ISSUE THREAD

**Issue by Rajaskank** [cakebox/cakebox#209]
Salut,

Lorsque que je veux changer le mot de passe par défaut (dans "auth.php") en passant par le site "https://www.dailycred.com/article/bcrypt-calculator" le hash donné ne fonctionne pas et il ne fourni pas non plus le salt.

En remettant les valeurs par défaut cela fonctionne parfaitement.

Une idée pour résoudre le problème ?

PS: j'ai bien les simple quote pour le hash

Merci.

**Comment by mpgn** [comment]
C'est une mission ce login 🗡 

Bon il faut faire sha256(tonmdp)+SALT dans le calculator

https://i.gyazo.com/666c28e2a7a5f0396c6f102aa8e8ac49.png

`9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08` => sha256(test)
`1589647820365489` => salt

**Comment by Rajaskank** [comment]
Wahou ! En effet j'avais pas compris ça ^^

Ça marche nickel merci beaucoup :)

**Comment by Galixte** [comment]
Une petite information dans le wiki serait un plus les rubriques concernées sont vides : « Add an user » & « Change the password of an user ».
