### ISSUE TITLE
Erreur multiuser

### ISSUE THREAD

**Issue by Rajaskank** [cakebox/cakebox#210]
C'est encore moi ^^

J'ai essayé de mettre un 2éme utilisateur (user2) mais du coup il ne prends plus en compte le 1er (user1)....

Voici mon fichier auth:

`<?php

/*
    User need to be authenticate
    1 Yes, 0 No
*/

$app["user.auth"] = 1;

/*
    Users informations
*/
$app["users"] = [
    [
        /*
          User rights
        */
        "user.name"                 => "user1",
        "user.password"             => 'XXX', //use https://www.dailycred.com/article/bcrypt-calculator with hash256(password)+salt or check the wiki to generate the password (default for user1 is foo)
        "user.salt"                 => "XXX", //long random number, change it for more security
        /*
          General configuration of Cakebox
        */
        "cakebox.root"              => "/home/dl/", // Root directory Cakebox have to scan don not put an extra "/" at the end
        "cakebox.access"            => "/access/", // Alias used in web server for direct access
        "cakebox.language"          => "fr", //Language of Cakebox. Could be : fr, en, it
        "cakebox.host"              => "XXX", //domain where cakebox is hosted
        /*
          Directory settings
        */
        "directory.ignoreDotFiles"  => true,
        "directory.ignore"          => "/(\incomplete)$/", // Regex for files exclusion. For exemple : "/(\.nfo|\.test)$/"
        /*
          Web player settings
        */
        "player.default_type"       => "divx",
        "player.auto_play"          => "true",
        /*
          User rights
        */
        "rights.canPlayMedia"       => true,
        "rights.canDownloadFile"    => true,
        "rights.canArchiveDirectory"=> false, //can archive folder
        "rights.canDelete"          => false, //can delete file or folder
        "rights.canCreate"          => false, //can create a folder
        "rights.canRename"          => false, //can rename file or folder
        "rights.canUpload"          => false, //can upload a file, activate this option only if you are sure to cakebox privately to avoid security issue
        /*
          Betaseries account
          NB: Ask API key here http://www.betaseries.com/api/
        */
        "bs.login"                  => "XXX",
        "bs.passwd"                 => "XXX",
        "bs.apikey"                 => "XXX"
    ]
];

$app["users"] = [
    [
        /*
          User rights
        */
        "user.name"                 => "user2",
        "user.password"             => 'XXX', //use https://www.dailycred.com/article/bc
        "user.salt"                 => "XXX", //long random number, change it for more security
        /*
          General configuration of Cakebox
        */
        "cakebox.root"              => "/home/dl/", // Root directory Cakebox have to scan don not put an extra "/" at the end
        "cakebox.access"            => "/access/", // Alias used in web server for direct access
        "cakebox.language"          => "fr", //Language of Cakebox. Could be : fr, en, it
        "cakebox.host"              => "XXX", //domain where cakebox is hosted
        /*
          Directory settings
        */
        "directory.ignoreDotFiles"  => true,
        "directory.ignore"          => "/(\incomplete|\Bureau|\Téléchargements|_h5ai)$/", // Regex for files exclusion. For exemple : "/(\.nfo|\.test)$/"
        /*
          Web player settings
        */
        "player.default_type"       => "divx",
        "player.auto_play"          => "true",
        /*
          User rights
        */
        "rights.canPlayMedia"       => true,
        "rights.canDownloadFile"    => true,
        "rights.canArchiveDirectory"=> false, //can archive folder
        "rights.canDelete"          => false, //can delete file or folder
        "rights.canCreate"          => false, //can create a folder
        "rights.canRename"          => false, //can rename file or folder
        "rights.canUpload"          => false, //can upload a file, activate this option only if you are sure to cakebox privately to avoid securi$
        /*
          Betaseries account
          NB: Ask API key here http://www.betaseries.com/api/
        */
        "bs.login"                  => "XXX",
        "bs.passwd"                 => "XXX",
        "bs.apikey"                 => "XXX"
    ]
];`

J'ai également essayé comme ceci mais j'ai une page blanche:

`<?php

/*
    User need to be authenticate
    1 Yes, 0 No
*/

$app["user.auth"] = 1;

/*
    Users informations
*/
$app["users"] = [
    [
        /*
          User rights
        */
        "user.name"                 => "user1",
        "user.password"             => 'XXX', //use https://www.dailycred.com/article/bcrypt-calculator with hash256(password)+salt or check the wiki to generate the password (default for user1 is foo)
        "user.salt"                 => "XXX", //long random number, change it for more security
        /*
          General configuration of Cakebox
        */
        "cakebox.root"              => "/home/dl/", // Root directory Cakebox have to scan don not put an extra "/" at the end
        "cakebox.access"            => "/access/", // Alias used in web server for direct access
        "cakebox.language"          => "fr", //Language of Cakebox. Could be : fr, en, it
        "cakebox.host"              => "XXX", //domain where cakebox is hosted
        /*
          Directory settings
        */
        "directory.ignoreDotFiles"  => true,
        "directory.ignore"          => "/(\incomplete)$/", // Regex for files exclusion. For exemple : "/(\.nfo|\.test)$/"
        /*
          Web player settings
        */
        "player.default_type"       => "divx",
        "player.auto_play"          => "true",
        /*
          User rights
        */
        "rights.canPlayMedia"       => true,
        "rights.canDownloadFile"    => true,
        "rights.canArchiveDirectory"=> false, //can archive folder
        "rights.canDelete"          => false, //can delete file or folder
        "rights.canCreate"          => false, //can create a folder
        "rights.canRename"          => false, //can rename file or folder
        "rights.canUpload"          => false, //can upload a file, activate this option only if you are sure to cakebox privately to avoid security issue
        /*
          Betaseries account
          NB: Ask API key here http://www.betaseries.com/api/
        */
        "bs.login"                  => "XXX",
        "bs.passwd"                 => "XXX",
        "bs.apikey"                 => "XXX"
    ]
    [
        /*
          User rights
        */
        "user.name"                 => "user2",
        "user.password"             => 'XXX', //use https://www.dailycred.com/article/bc
        "user.salt"                 => "XXX", //long random number, change it for more security
        /*
          General configuration of Cakebox
        */
        "cakebox.root"              => "/home/dl/", // Root directory Cakebox have to scan don not put an extra "/" at the end
        "cakebox.access"            => "/access/", // Alias used in web server for direct access
        "cakebox.language"          => "fr", //Language of Cakebox. Could be : fr, en, it
        "cakebox.host"              => "XXX", //domain where cakebox is hosted
        /*
          Directory settings
        */
        "directory.ignoreDotFiles"  => true,
        "directory.ignore"          => "/(\incomplete|\Bureau|\Téléchargements|_h5ai)$/", // Regex for files exclusion. For exemple : "/(\.nfo|\.test)$/"
        /*
          Web player settings
        */
        "player.default_type"       => "divx",
        "player.auto_play"          => "true",
        /*
          User rights
        */
        "rights.canPlayMedia"       => true,
        "rights.canDownloadFile"    => true,
        "rights.canArchiveDirectory"=> false, //can archive folder
        "rights.canDelete"          => false, //can delete file or folder
        "rights.canCreate"          => false, //can create a folder
        "rights.canRename"          => false, //can rename file or folder
        "rights.canUpload"          => false, //can upload a file, activate this option only if you are sure to cakebox privately to avoid securi$
        /*
          Betaseries account
          NB: Ask API key here http://www.betaseries.com/api/
        */
        "bs.login"                  => "XXX",
        "bs.passwd"                 => "XXX",
        "bs.apikey"                 => "XXX"
    ]
];`

**Comment by ahyear** [comment]
moi j'aurai utilisé le second code mais avec un virgule entre les 2 users:
"bs.apikey" => "XXX"
],
[
/
User rights

**Comment by Rajaskank** [comment]
Merci pour ta réponse, je n'ai plus la page blanche mais le "user1" ne marche toujours pas

**Comment by mpgn** [comment]
Je regarde dans la semaine ou ce week-end

**Comment by ahyear** [comment]
as tu essayé en navigation privée? as-tu le meme resultat?

**Comment by Rajaskank** [comment]
@mpgn cool merci ;-)

@ahyear non j'ai pas fait le test, je te dis quoi quand ça sera fait

**Comment by mpgn** [comment]
J'ai testé le multi user et ca fonctionne bien pour moi. Voila mon fichier de conf : 

test1 / test
test2 / test

```
<?php

/*
    User need to be authenticate 
    1 Yes, 0 No
*/

$app["user.auth"] = 1;

/* 
    Users informations
*/
$app["users"] = [
    [
        /*
          User rights
        */
        "user.name"                 => "user1",
        "user.password"             => '$2a$12$qr/RZNH8BBFYUcY46.Ygner2TxxYRWBfVHiAmiVZDoVQAA8.XXmIS', //use https://www.dailycred.com/article/bcrypt-calculator with hash256(password)+salt or check the wiki to generate the password (default for user1 is foo)
        "user.salt"                 => "1589647820365489", //long random number, change it for more security
        /*
          General configuration of Cakebox
        */
        "cakebox.root"              => "C:\Users\mpgn\Videos", // Root directory Cakebox have to scan don not put an extra "/" at the end
        "cakebox.access"            => "/access/", // Alias used in web server for direct access
        "cakebox.language"          => "fr", //Language of Cakebox. Could be : fr, en, it
        "cakebox.host"              => "cakebox.dev", //domain where cakebox is hosted
        /*
          Directory settings
        */
        "directory.ignoreDotFiles"  => true,
        "directory.ignore"          => "", // Regex for files exclusion. For exemple : "/(\.nfo|\.test)$/"
        /*
          Web player settings
        */
        "player.default_type"       => "html5",
        "player.auto_play"          => "false",
        /*
          User rights
        */
        "rights.canPlayMedia"       => true,
        "rights.canDownloadFile"    => true,
        "rights.canArchiveDirectory"=> true, //can archive folder
        "rights.canDelete"          => true, //can delete file or folder
        "rights.canCreate"          => true, //can create a folder
        "rights.canRename"          => true, //can rename file or folder
        "rights.canUpload"          => true, //can upload a file, activate this option only if you are sure to cakebox privately to avoid security issue
        /*
          Betaseries account
          NB: Ask API key here http://www.betaseries.com/api/
        */
        "bs.login"                  => "",
        "bs.passwd"                 => "",
        "bs.apikey"                 => ""
    ],
    [
        /*
          User rights
        */
        "user.name"                 => "user2",
        "user.password"             => '$2a$12$qr/RZNH8BBFYUcY46.Ygner2TxxYRWBfVHiAmiVZDoVQAA8.XXmIS', //use https://www.dailycred.com/article/bcrypt-calculator with hash256(password)+salt or check the wiki to generate the password (default for user1 is foo)
        "user.salt"                 => "1589647820365489", //long random number, change it for more security
        /*
          General configuration of Cakebox
        */
        "cakebox.root"              => "C:\Users\mpgn\Videos\Desktop", // Root directory Cakebox have to scan don not put an extra "/" at the end
        "cakebox.access"            => "/access/", // Alias used in web server for direct access
        "cakebox.language"          => "fr", //Language of Cakebox. Could be : fr, en, it
        "cakebox.host"              => "cakebox.dev", //domain where cakebox is hosted
        /*
          Directory settings
        */
        "directory.ignoreDotFiles"  => true,
        "directory.ignore"          => "", // Regex for files exclusion. For exemple : "/(\.nfo|\.test)$/"
        /*
          Web player settings
        */
        "player.default_type"       => "html5",
        "player.auto_play"          => "false",
        /*
          User rights
        */
        "rights.canPlayMedia"       => true,
        "rights.canDownloadFile"    => true,
        "rights.canArchiveDirectory"=> true, //can archive folder
        "rights.canDelete"          => true, //can delete file or folder
        "rights.canCreate"          => true, //can create a folder
        "rights.canRename"          => true, //can rename file or folder
        "rights.canUpload"          => true, //can upload a file, activate this option only if you are sure to cakebox privately to avoid security issue
        /*
          Betaseries account
          NB: Ask API key here http://www.betaseries.com/api/
        */
        "bs.login"                  => "",
        "bs.passwd"                 => "",
        "bs.apikey"                 => ""
    ]
];

```

**Comment by Rajaskank** [comment]
Ok super ça marche également pour moi, j'ai dû faire un mauvais c/c pour le mot de passe de l'user1 pourtant quand je virais l'user2 ça marchait... Enfin bref problème résolu je vous remercie et je clôture ;)
