### ISSUE TITLE
Annonce script d'installation

### ISSUE THREAD

**Issue by Patlol** [cakebox/cakebox#211]
Bonjour,

J'ai écrit un script d'installation testé sur serveur ovh vps et kimsufi de

- apache ou nginx et php
- rtorrent en daemon
- rutorrent multi-utilisateur
- cakebox light multi-utilisateur
- VPN
- webmin

dite-moi ce que vous en pensez
[https://github.com/Patlol/Handy-Install-Web-Server-ruTorrent-](url)

Merci de vos retour sur [https://github.com/Patlol/Handy-Install-Web-Server-ruTorrent-/issues](url)

**Comment by Galixte** [comment]
Ton lien ne fonctionne pas, celui oui : https://github.com/Patlol/Handy-Install-Web-Server-ruTorrent-

Merci pour ton travail. ;)

**Comment by mpgn** [comment]
project is deprecated, check https://github.com/cakebox/cakebox/issues/216

**Comment by Galixte** [comment]
Je le sais, aucun rapport avec ma remarque. ;)
