### ISSUE TITLE
404 au téléchargement

### ISSUE THREAD

**Issue by azope** [cakebox/cakebox#214]
Bonjour,
sur 1.8.6 de Cakebox-light
lorsque je clique sur "télécharger le fichier" j'ai une erreur 404 
404 Not Found
nginx/1.10.0 (Ubuntu)

avec cet url : http:/<mon IP>/access/xxxx.mp4
la même installation avec apache fonctionne sans problème !
fichiers de config nginx et cakebox [ici](https://gist.github.com/azope/7ac46d7085037ff4a6c9463ebf1d496a)
Pour le streaming je n'ai pas de message d'erreur mais la vidéo ne démarre pas. J'ai alors l'icone du clap de cinéma.
Merci pour votre aide

**Comment by mpgn** [comment]
project is deprecated, check https://github.com/cakebox/cakebox/issues/216
