### ISSUE TITLE
CAKEBOX - An error occurred. (NGINX)

### ISSUE THREAD

**Issue by Daaaam** [cakebox/cakebox#215]
Hi.

I have an error message when I access http://xxx/cakebox
http://hpics.li/694ea82

**default.php :** 

General configuration of Cakebox
*/
$app["cakebox.root"] = "/home/**username**/torrents/"; // Root directory Cakebox have to scan
$app["cakebox.access"] = "/cakebox/**username**/"; // Alias used in web server for direct access
$app["cakebox.language"] = "fr"; //Language of Cakebox. Could be : fr, en
$app["cakebox.host"] = "I"; //domain where cakebox is hosted

**rutorrent.conf :**

 location /cakebox/ {
        rewrite ^/cakebox(/.*)$ $1 break;
        proxy_pass http://127.0.0.1:81;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
    }

    location /cakebox/**username**/ {
        alias /home/**username**/torrents/;
        add_header Content-Disposition "attachment";
        satisfy any;
        allow all;
    }

    location /cakebox/**username**/ {
       alias /home/**username**/torrents/;
       add_header Content-Disposition "attachment";
       satisfy any;
       allow all;
    }

**Comment by mpgn** [comment]
project is deprecated, check https://github.com/cakebox/cakebox/issues/216
