### ISSUE TITLE
Que devient cakebox ?

### ISSUE THREAD

**Issue by Patlol** [cakebox/cakebox#216]
Salut,
j'ai des problèmes avec cakebox sur nginx (c'est ok avec apache) : erreur 404 au téléchargement d'un fichier depuis cakebox. voir l'[issue](https://github.com/Patlol/Handy-Install-Web-Server-ruTorrent-/issues/3#issuecomment-294284664) en lien.

Je vois qu'ici aussi il y a 2 issues sur le même sujet qui sont restées sans réponse de votre part.
Avez-vous rencontré le même problème ?

D'autre part quel avenir pour cakebox sachant que la gestion des plugins a été réduite à peau de chagrin sur les navigateurs et qu'il n'y a plus ni vlc ni divX de dispo. 
Au vu des dates de vos derniers messages et des commits, je me pose des questions sur la pérennité de ce projet. Pouvez-vous me donner une réponse ?

**Comment by mpgn** [comment]
Pour résumer : Est-ce que c'est #deprecated ?

**Comment by tuxity** [comment]
Salut @PatlolC'est une très bonne question.

Le + de cakebox était de pouvoir voir des vidéos en streaming sans avoir besoin d'installer toute une usine a gaz. L'installation de plugins était souvent nécessaire suivant les types d'encode utilisé sur vos fichiers.

Depuis un bout de temps déjà, Chrome a deprecated NPAPI qui était utilisé par les plugins, puis l'a complètement enlevé (pour des raisons de sécurité). Les autres navigateurs ne devrait plus tarder à l'enlever aussi https://en.wikipedia.org/wiki/NPAPI#Browser_support Malheureusement il n'existe pas (pour le moment) d'autres solutions, en fait si, une seule, le support de la balise <video==>==</video==>== html5. Mais elle ne peut pas lire tous les formats et les pistes de sous-titres doivent être bien configurés ...

Depuis un bout de temps je pense à deprecated le projet, ou tout nettoyer et virer les différents lecteurs, ou attendre que quelque chose de nouveau sorte ...Cependant, bien que le projet puisse être deprecated, j'ai quelques idées de nouveaux projets pour l'organisation cakebox qui peuvent être très stylés. Mais malheureusement plus autant de temps qu'avant pour les faire 😢 #vieux

On peut utiliser ce thread pour brainstormer si vous le souhaitez.

**Comment by Patlol** [comment]
@tuxity Brainstormons, brainstormons ... 

- Depuis la version 52 le dernier navigateur à accepter les plugins vlc divx était firefox, c'est donc acté. Reste la version ESR jusqu'en 2018. La version 53 fera le ménage sur les extensions, il risque d'y avoir encore pas mal de surprise ... Donc exit les navigateurs.

- Je ne m'y connais pas vraiment en technologie de streaming, ce que je constate c'est qu'il y a 2 grandes solutions à ma connaissance : Kodi (ex XBMC) et Plex (dérivé de XBMC) tout 2, si j'ai bien compris, installé en local.

- Pour moi ce sont de gros "truc" très jolis mais un peu usine à gaz ... je me trompe peut-être

- D'un autre coté il y a la technologie cloud, avec en libre owncloud, qui permet de communiquer facilement entre local et distant. La partie gestion de fichier distant, rapatriment en local et liens de partage est réglé. Reste le streaming.

- Une question comme ça ... brainstormons tous en coeur, y aurait-il une piste à ce niveau en imaginant une appli owncloud, pour faire passer le flux du serveur à un lecteur en local type vlc ???

**Comment by tuxity** [comment]
La balise html5 je me souviens qu'elle lisait pas l'audio des .mkv

Depuis 1 ans ou 2 maintenant j'utilise Plex. C'est pas mal et pas super chiant a installer. C'est dispo via ton navigateur, ios, android, nvidia shield etc ... Le seul point négatif c'est que les utilisateurs ne sont pas super bien géré a mon gout, et en plus tu dois payer pour pouvoir en faire... Mais tu peux transcoder, il y a pas mal d'addons  aussi

Pour ce que est de owncloud, je vais me renseigner. Je ne connais pas du tout.

**Comment by mpgn** [comment]
@tuxity Kodi est vraiment pas mal ! 

Faut pas oublié que Cakebox a été créé à une époque où il n'y avait pas autant d'alternative et surtout c'est vraiment pas 'click click up ca fonctionne' :)

**Comment by tuxity** [comment]
Je suis assez d'accord, a l'époque il n'y avait pas autant d'alternatives. Ca me paraît être une bonne conclusion !

Kodi est pas mal aussi oui, je l'utilisais avant Plex

**Comment by tuxity** [comment]
Et puis si on arrête, on pourra ce concentrer sur d'autres projets (toujours dans le même domaine)

**Comment by Patlol** [comment]
oui je pense qu'il faut s'orienté vers d'autres projets utilisant d'autres technologies.
**Pour owncloud** 
- il y a un application officiel qui utilise video.js mais on reste bien sûr sur la balise html, il peut streamer les  .mp4, .ogg, .flv and .webm :)
- il y avait d'autres app, qui ne sont plus maintenues depuis l'apparition de l'app ci-dessus, qui utilisait le transcodage et qui avait un champs de lecture plus large.

**vlc** 

- Si j'ai bien compris vlc propose une solution de srteaming  [page du site officiel](https://www.videolan.org/vlc/streaming.html)    [article 1](http://www.makeuseof.com/tag/create-linux-vlc-streaming-media-server-home/) [article 2](http://minimaldevelop.com/blog/how-to-setup-streaming-server-via-vlc/) Je n'ai pas approfondi plus que ça. Mais c'est la seule piste que j'ai trouvé.

Je pense à mon humble avis que vlc ou le transcodage (avec tous ses inconvénients) sont les pistes possible, en tout cas je n'en voie pas d'autre, si l'on veut proposer un projet dans ce sens

Qu'en pensez-vous ?

**Comment by tuxity** [comment]
Je pense que la solution de vlc est beaucoup trop "usine a gaz", a la base cakebox était un truc simple, et facile a installer.

Je pense deprecate le projet, et nous concentrer sur [donuts](https://github.com/cakebox/donuts) ou [cheesecake](https://github.com/cakebox/cheesecake)

**Comment by tuxity** [comment]
https://github.com/cakebox/cakebox/commit/4fe1d0d3b38b74f5ab4ec38d36d784f986d9691e

**Comment by Patlol** [comment]
Bon ben cela a le mérite d'être clair, pas de streaming, en tout cas dans un avenir proche. :(

**Comment by sohelzerdoumi** [comment]
Voici mon alternative
https://github.com/filebrowser/filebrowser

**Comment by Galixte** [comment]
@sohelzerdoumi c’est mullti-langue ?

**Comment by sohelzerdoumi** [comment]
@Galixte Oui, tu peux trouver plus d'infos ici
https://filebrowser.github.io/configuration/

**Comment by Patlol** [comment]
Certainement une très bonne alternative pour un navigateur de fichiers, mais malheureusement rien pour le streaming ...
